import { X509Certificate } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { Builder, Context, LocalSigner, Reader } from '@contentauth/c2pa-node';
import type { ContentCredentialsStamp, DisclosureStamp } from '@rideo/shared';
import type { Logger } from '../domain/deps';
import type { Metrics } from '../metrics';
import { createDevSigner } from './dev-cert';

/**
 * C2PA Content Credentials for takes and exports (docs/design/provenance.md#manifests): manifests are built and
 * signed with the official SDK (@contentauth/c2pa-node, the Rust c2pa-rs core) and read back for verification.
 */

export const TRAINED = 'http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia';
export const COMPOSITE_AI =
  'http://cv.iptc.org/newscodes/digitalsourcetype/compositeWithTrainedAlgorithmicMedia';
export const COMPOSITE = 'http://cv.iptc.org/newscodes/digitalsourcetype/composite';
const AI_SOURCE_TYPES = new Set([
  TRAINED,
  COMPOSITE_AI,
  'http://cv.iptc.org/newscodes/digitalsourcetype/algorithmicMedia',
]);
export const WATERMARK_SOFT_BINDING = 'org.rideo.watermark.1';

export interface C2paConfig {
  enabled: boolean;
  /** PEM chain (leaf first) or a path to it. */
  cert?: string;
  /** PEM private key or a path to it. */
  key?: string;
  tsaUrl?: string;
  /** PEM bundle (or a path) of CAs whose signatures read as `trusted`. */
  trustAnchors?: string;
  dataDir: string;
  generator: { name: string; version: string };
}

export interface TakeManifest {
  input: string;
  output: string;
  title: string;
  projectId: string;
  asset: { clipId: string; shotId: string; takeId: string };
  watermarkId: string | null;
  models: { imageModel?: string; videoModel?: string };
  consistency: { status: string; score: number; judge: string };
  /** The verified keyframe the video started from (a local PNG). */
  keyframe?: string | null;
  /** A derived take: its parent take (a local MP4 with its own manifest) and the operation (take-editing.md). */
  parent?: {
    path: string;
    /** `dub`: lip-synced to a dubbed line (docs/design/localization.md#dubbing). */
    op: 'edit' | 'extend' | 'dub';
    kind?: string;
    instruction?: string;
    seconds?: number;
  } | null;
}

export interface ExportIngredient {
  /** Local path of the file (its own manifest, if any, is carried over). */
  path: string;
  mime: string;
  title: string;
  /** Generated by AI (takes, generated music) rather than captured or uploaded. */
  generated: boolean;
}

export interface ExportManifest {
  input: string;
  output: string;
  title: string;
  projectId: string;
  exportId: string;
  timelineCommit: string | null;
  watermarkId: string | null;
  ingredients: ExportIngredient[];
  disclosure: DisclosureStamp | null;
}

/** A stem of an export (docs/design/post-audio.md#stems): the audio sources of one stem, mixed. */
export interface StemManifest {
  input: string;
  output: string;
  title: string;
  projectId: string;
  exportId: string;
  role: 'dialogue' | 'music' | 'effects';
  timelineCommit: string | null;
  ingredients: ExportIngredient[];
}

export interface ContentCredentials {
  present: boolean;
  state?: 'invalid' | 'valid' | 'trusted';
  issues?: string[];
  manifest?: string;
  signer?: { commonName?: string; issuer?: string };
  signedByThisStudio?: boolean;
  claimGenerator?: string;
  title?: string;
  aiGenerated?: boolean;
  digitalSourceType?: string;
  actions?: string[];
  ingredients?: number;
  watermarkId?: string | null;
  disclosure?: { label: boolean; text?: string; reason?: string | null } | null;
  error?: string;
}

type Json = Record<string, unknown>;

async function pemOrFile(value: string): Promise<string> {
  return value.includes('-----BEGIN') ? value : readFile(value, 'utf8');
}

function decimalSerial(hex: string): string {
  return BigInt(`0x${hex}`).toString(10);
}

export class C2paService {
  private signer: LocalSigner | null = null;
  private serial: string | null = null;
  private signerName = '';
  private readContext: Context | null = null;
  private fastContext: Context | null = null;

  constructor(
    private readonly cfg: C2paConfig,
    private readonly deps: { log: Logger; metrics: Metrics },
  ) {}

  get enabled(): boolean {
    return this.cfg.enabled && this.signer !== null;
  }

  /** Loads the configured certificate, or creates (once) and reuses a development signer in the data dir. */
  async init(): Promise<void> {
    const anchors = this.cfg.trustAnchors ? await pemOrFile(this.cfg.trustAnchors) : undefined;
    this.readContext = new Context(anchors ? { trust: { trustAnchors: anchors } } : {});
    this.fastContext = new Context({ verify: { verifyAfterReading: false } });
    if (!this.cfg.enabled) return;
    let chain: string;
    let key: string;
    if (this.cfg.cert && this.cfg.key) {
      chain = await pemOrFile(this.cfg.cert);
      key = await pemOrFile(this.cfg.key);
    } else {
      const dir = join(this.cfg.dataDir, 'c2pa');
      const paths = { chain: join(dir, 'cert.pem'), key: join(dir, 'key.pem'), ca: join(dir, 'ca.pem') };
      if (existsSync(paths.chain) && existsSync(paths.key)) {
        chain = await readFile(paths.chain, 'utf8');
        key = await readFile(paths.key, 'utf8');
      } else {
        const dev = createDevSigner(this.cfg.generator.name);
        await mkdir(dir, { recursive: true });
        await writeFile(paths.chain, dev.chainPem);
        await writeFile(paths.ca, dev.caPem);
        await writeFile(paths.key, dev.keyPem, { mode: 0o600 });
        chain = dev.chainPem;
        key = dev.keyPem;
      }
      this.deps.log.warn(
        { dir },
        'using a development C2PA signer: validators report it as untrusted (set RIDEO_C2PA_CERT and RIDEO_C2PA_KEY in production)',
      );
    }
    const { createPrivateKey } = await import('node:crypto');
    const pkcs8 = createPrivateKey(key).export({ type: 'pkcs8', format: 'pem' }).toString();
    this.signer = LocalSigner.newSigner(Buffer.from(chain), Buffer.from(pkcs8), 'es256', this.cfg.tsaUrl);
    const leaf = new X509Certificate(chain.slice(0, chain.indexOf('-----END CERTIFICATE-----') + 25));
    this.serial = decimalSerial(leaf.serialNumber);
    this.signerName = /CN=([^\n,]+)/.exec(leaf.subject)?.[1] ?? leaf.subject;
  }

  private async sign(
    definition: Json,
    input: string,
    output: string,
    ingredients: {
      json: Json;
      path: string;
      mime: string;
    }[],
    mime = 'video/mp4',
  ): Promise<ContentCredentialsStamp> {
    if (!this.signer) throw new Error('C2PA signing is not configured');
    try {
      const builder = await Builder.withJsonAsync(definition as never);
      for (const ing of ingredients)
        await builder.addIngredient(JSON.stringify(ing.json), { path: ing.path, mimeType: ing.mime });
      builder.sign(this.signer, { path: input, mimeType: mime }, { path: output });
      const reader = await Reader.fromAsset({ path: output, mimeType: mime }, this.fastContext!);
      const manifest = String((reader?.json() as Json | undefined)?.active_manifest ?? '');
      this.deps.metrics.c2pa.inc({ op: 'sign', result: 'ok' });
      return {
        manifest,
        signer: this.signerName,
        signedAt: new Date().toISOString(),
        ...(ingredients.length ? { ingredients: ingredients.length } : {}),
      };
    } catch (err) {
      this.deps.metrics.c2pa.inc({ op: 'sign', result: 'error' });
      throw err;
    }
  }

  private generatorInfo() {
    return [{ name: this.cfg.generator.name, version: this.cfg.generator.version }];
  }

  private watermarkParts(watermarkId: string | null) {
    if (!watermarkId) return { actions: [], assertions: [] };
    return {
      actions: [{ action: 'c2pa.watermarked', parameters: { watermark: watermarkId } }],
      assertions: [
        {
          label: 'c2pa.soft-binding',
          data: {
            alg: WATERMARK_SOFT_BINDING,
            blocks: [{ scope: {}, value: Buffer.from(watermarkId).toString('base64') }],
          },
        },
      ],
    };
  }

  /** A generated take: created by the video model, watermarked, its keyframe as the input ingredient. */
  async signTake(m: TakeManifest): Promise<ContentCredentialsStamp> {
    const wm = this.watermarkParts(m.watermarkId);
    const keyframe = m.keyframe
      ? [
          {
            json: { title: 'keyframe.png', format: 'image/png', relationship: 'inputTo', label: 'keyframe' },
            path: m.keyframe,
            mime: 'image/png',
          },
        ]
      : [];
    const parent = m.parent
      ? [
          {
            json: {
              title: 'parent take.mp4',
              format: 'video/mp4',
              relationship: 'parentOf',
              label: 'parent',
            },
            path: m.parent.path,
            mime: 'video/mp4',
          },
        ]
      : [];
    return this.sign(
      {
        claim_generator_info: this.generatorInfo(),
        title: m.title,
        format: 'video/mp4',
        assertions: [
          {
            label: 'c2pa.actions.v2',
            data: {
              actions: [
                // A derived take (an edit or an extension) opens its parent and edits it with AI; a new take is
                // created. A manifest has exactly one of the two.
                ...(m.parent
                  ? [
                      {
                        action: 'c2pa.opened',
                        parameters: { ingredientIds: ['parent'] },
                      },
                      {
                        action: 'c2pa.edited',
                        digitalSourceType: TRAINED,
                        softwareAgent: { name: m.models.videoModel || 'mm-gateway' },
                        parameters: {
                          gateway: 'mm-gateway',
                          operation: m.parent.op,
                          ...(m.parent.kind ? { kind: m.parent.kind } : {}),
                          ...(m.parent.instruction ? { instruction: m.parent.instruction } : {}),
                          ...(m.parent.seconds ? { seconds: m.parent.seconds } : {}),
                          ...(m.models.videoModel ? { videoModel: m.models.videoModel } : {}),
                        },
                      },
                    ]
                  : [
                      {
                        action: 'c2pa.created',
                        digitalSourceType: TRAINED,
                        softwareAgent: { name: m.models.videoModel || 'mm-gateway' },
                        parameters: {
                          gateway: 'mm-gateway',
                          ...(m.models.imageModel ? { imageModel: m.models.imageModel } : {}),
                          ...(m.models.videoModel ? { videoModel: m.models.videoModel } : {}),
                          ...(keyframe.length ? { ingredientIds: ['keyframe'] } : {}),
                        },
                      },
                    ]),
                ...wm.actions,
              ],
            },
          },
          ...wm.assertions,
          {
            label: 'org.rideo.provenance',
            data: {
              project: m.projectId,
              asset: { kind: 'take', ...m.asset },
              consistency: m.consistency,
            },
          },
        ],
      },
      m.input,
      m.output,
      [...parent, ...keyframe],
    );
  }

  /**
   * Frames generated to extend an item of the cut (docs/design/take-editing.md#generative-extend-in-the-editor):
   * created by AI from the edge frame of the item.
   */
  async signExtension(m: {
    input: string;
    output: string;
    title: string;
    projectId: string;
    resourceId: string;
    watermarkId: string | null;
    videoModel?: string;
    edgeFrame: string;
  }): Promise<ContentCredentialsStamp> {
    const wm = this.watermarkParts(m.watermarkId);
    return this.sign(
      {
        claim_generator_info: this.generatorInfo(),
        title: m.title,
        format: 'video/mp4',
        assertions: [
          {
            label: 'c2pa.actions.v2',
            data: {
              actions: [
                {
                  action: 'c2pa.created',
                  digitalSourceType: TRAINED,
                  softwareAgent: { name: m.videoModel || 'mm-gateway' },
                  parameters: {
                    gateway: 'mm-gateway',
                    operation: 'extend',
                    ...(m.videoModel ? { videoModel: m.videoModel } : {}),
                    ingredientIds: ['edge-frame'],
                  },
                },
                ...wm.actions,
              ],
            },
          },
          ...wm.assertions,
          {
            label: 'org.rideo.provenance',
            data: { project: m.projectId, asset: { kind: 'extension', id: m.resourceId } },
          },
        ],
      },
      m.input,
      m.output,
      [
        {
          json: {
            title: 'edge frame.png',
            format: 'image/png',
            relationship: 'inputTo',
            label: 'edge-frame',
          },
          path: m.edgeFrame,
          mime: 'image/png',
        },
      ],
    );
  }

  /** An export: a composite placing its takes and resources, watermarked, with the disclosure it shows. */
  async signExport(m: ExportManifest): Promise<ContentCredentialsStamp> {
    const wm = this.watermarkParts(m.watermarkId);
    const labels = m.ingredients.map((_, i) => `ingredient-${i + 1}`);
    const ai = m.ingredients.some((i) => i.generated);
    return this.sign(
      {
        claim_generator_info: this.generatorInfo(),
        title: m.title,
        format: 'video/mp4',
        assertions: [
          {
            label: 'c2pa.actions.v2',
            data: {
              actions: [
                {
                  action: 'c2pa.created',
                  digitalSourceType: ai ? COMPOSITE_AI : COMPOSITE,
                  softwareAgent: { name: this.cfg.generator.name },
                },
                ...(labels.length ? [{ action: 'c2pa.placed', parameters: { ingredientIds: labels } }] : []),
                ...wm.actions,
              ],
            },
          },
          ...wm.assertions,
          {
            label: 'org.rideo.provenance',
            data: {
              project: m.projectId,
              asset: { kind: 'export', exportId: m.exportId },
              timelineCommit: m.timelineCommit,
            },
          },
          {
            label: 'org.rideo.disclosure',
            data: m.disclosure
              ? { label: m.disclosure.label, text: m.disclosure.text, reason: m.disclosure.reason }
              : { label: false, reason: null },
          },
        ],
      },
      m.input,
      m.output,
      m.ingredients.map((ing, i) => ({
        json: { title: ing.title, format: ing.mime, relationship: 'componentOf', label: labels[i] },
        path: ing.path,
        mime: ing.mime,
      })),
    );
  }

  /** A stem of an export: a WAV composite placing the stem's audio sources (no watermark: that is in the picture). */
  async signStem(m: StemManifest): Promise<ContentCredentialsStamp> {
    const labels = m.ingredients.map((_, i) => `ingredient-${i + 1}`);
    const ai = m.ingredients.some((i) => i.generated);
    return this.sign(
      {
        claim_generator_info: this.generatorInfo(),
        title: m.title,
        format: 'audio/wav',
        assertions: [
          {
            label: 'c2pa.actions.v2',
            data: {
              actions: [
                {
                  action: 'c2pa.created',
                  digitalSourceType: ai ? COMPOSITE_AI : COMPOSITE,
                  softwareAgent: { name: this.cfg.generator.name },
                },
                ...(labels.length ? [{ action: 'c2pa.placed', parameters: { ingredientIds: labels } }] : []),
              ],
            },
          },
          {
            label: 'org.rideo.provenance',
            data: {
              project: m.projectId,
              asset: { kind: 'stem', exportId: m.exportId, stem: m.role },
              timelineCommit: m.timelineCommit,
            },
          },
        ],
      },
      m.input,
      m.output,
      m.ingredients.map((ing, i) => ({
        json: { title: ing.title, format: ing.mime, relationship: 'componentOf', label: labels[i] },
        path: ing.path,
        mime: ing.mime,
      })),
      'audio/wav',
    );
  }

  /** Reads and validates the manifest store of a media file (`present: false` when there is none). */
  async read(path: string, mime = 'video/mp4'): Promise<ContentCredentials> {
    try {
      const reader = await Reader.fromAsset({ path, mimeType: mime }, this.readContext ?? undefined);
      if (!reader) {
        this.deps.metrics.c2pa.inc({ op: 'read', result: 'none' });
        return { present: false };
      }
      const store = reader.json() as Json;
      const active = reader.getActive() as Json | null;
      const assertions = ((active?.assertions as Json[] | undefined) ?? []).map((a) => ({
        label: String(a.label),
        data: (a.data ?? {}) as Json,
      }));
      const actions = assertions
        .filter((a) => a.label.startsWith('c2pa.actions'))
        .flatMap((a) => ((a.data.actions as Json[] | undefined) ?? []) as Json[]);
      const sourceType = actions
        .map((a) => a.digitalSourceType)
        .find((t): t is string => typeof t === 'string');
      const binding = assertions.find(
        (a) => a.label === 'c2pa.soft-binding' && a.data.alg === WATERMARK_SOFT_BINDING,
      );
      const block = (binding?.data.blocks as { value?: string }[] | undefined)?.[0]?.value;
      const disclosure = assertions.find((a) => a.label === 'org.rideo.disclosure')?.data;
      const signature = (active?.signature_info ?? {}) as Json;
      const statuses = [
        ...(((store.validation_status as Json[] | undefined) ?? []) as Json[]),
        ...((((store.validation_results as Json | undefined)?.activeManifest as Json | undefined)?.failure as
          | Json[]
          | undefined) ?? []),
      ];
      const issues = [...new Set(statuses.map((s) => String(s.code)))].filter(
        (c) => c !== 'signingCredential.untrusted',
      );
      const state = String(store.validation_state ?? '').toLowerCase();
      const generator = (active?.claim_generator_info as Json[] | undefined)?.[0];
      this.deps.metrics.c2pa.inc({ op: 'read', result: state || 'unknown' });
      return {
        present: true,
        state: state === 'trusted' ? 'trusted' : state === 'invalid' || issues.length ? 'invalid' : 'valid',
        issues,
        manifest: String(store.active_manifest ?? ''),
        signer: {
          ...(signature.common_name ? { commonName: String(signature.common_name) } : {}),
          ...(signature.issuer ? { issuer: String(signature.issuer) } : {}),
        },
        signedByThisStudio: !!this.serial && String(signature.cert_serial_number ?? '') === this.serial,
        ...(generator ? { claimGenerator: `${generator.name ?? ''} ${generator.version ?? ''}`.trim() } : {}),
        ...(active?.title ? { title: String(active.title) } : {}),
        aiGenerated: !!sourceType && AI_SOURCE_TYPES.has(sourceType),
        ...(sourceType ? { digitalSourceType: sourceType } : {}),
        actions: actions.map((a) => String(a.action)),
        ingredients: ((active?.ingredients as unknown[] | undefined) ?? []).length,
        watermarkId: block ? Buffer.from(block, 'base64').toString('utf8') : null,
        disclosure: disclosure
          ? {
              label: !!disclosure.label,
              ...(disclosure.text ? { text: String(disclosure.text) } : {}),
              reason: (disclosure.reason as string | null | undefined) ?? null,
            }
          : null,
      };
    } catch (err) {
      this.deps.metrics.c2pa.inc({ op: 'read', result: 'error' });
      this.deps.log.warn({ err: (err as Error).message, path }, 'could not read C2PA manifest');
      return { present: false, error: (err as Error).message.slice(0, 300) };
    }
  }
}
